### ISSUE TITLE
Socks代理如何指定用户名和密码

### ISSUE THREAD

**Issue by patrickwangqy** [YtFlow/Maple#11]
Socks代理如何指定用户名和密码

**Comment by bdbai** [comment]
看起来 Leaf 没有还支持 SOCKS5 代理的鉴权，已经反馈给上游了。

**Comment by jtans** [comment]
+1

**Comment by gogcwy** [comment]
不知道是否有新的更新，版本好久没变化，极其需要带账号密码的socks5配置

**Comment by jtans** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我不在线，无法亲自回复您的邮件。不过我会尽快给您回复滴。

**Comment by bdbai** [comment]
https://github.com/YtFlow/Maple/releases/tag/v0.9.0 合并的上游版本应该已经支持了。
