### ISSUE TITLE
uwp应用无法连接网络

### ISSUE THREAD

**Issue by patrickwangqy** [YtFlow/Maple#12]
开启之后，uwp应用无法连接网络
![image](https://user-images.githubusercontent.com/22412010/119748189-e6358000-bec6-11eb-9191-0f11677cd9e9.png)

**Comment by bdbai** [comment]
你的 VPN 配置是点按钮一键生成的还是手动输入的？

**Comment by patrickwangqy** [comment]
点击generate profile生成的

**Comment by bdbai** [comment]
删除掉生成的 VPN 连接，然后手动创建一个再试一下？

**Comment by patrickwangqy** [comment]
手动添加的可以
