### ISSUE TITLE
geoip 无效

### ISSUE THREAD

**Issue by skyairun** [YtFlow/Maple#13]
配置中geoip 不起作用

[Rule]
GEOIP, cn, Direct
GEOIP, private, Direct

FINAL, Proxy

chrome 中全部代理

**Comment by bdbai** [comment]
在 `[General]` 一节中添加：
```ini
routing-domain-resolve = true
```
即可。见 https://github.com/eycorsican/leaf/issues/122 。

这个选项 Leaf 文档没写，可以考虑给 Leaf 开个 issue？

**Comment by skyairun** [comment]
我添加了，并没有效果

我还根据这个
https://github.com/eycorsican/leaf/issues/123#issuecomment-817287610
添加了dns-interface = 192.168.1.101，还是没用，关闭fake dns 也不行

还有个问题，dns-server = 不能指定为system，指定了不能连接vpn

**Comment by bdbai** [comment]
> 我添加了，并没有效果

配置区域存在 `geo.mmdb` 文件吗？如果没有的话可以参考 https://github.com/eycorsican/ileaf/blob/main/misc/download_data.sh#L10 获取一份，拖进来改名然后再试一下。

> dns-interface = 192.168.1.101

建议这里不要改接口相关的配置，Maple 会在启动 Leaf 时把 Setting 中的接口设置注入进去。通常只要保证 `dns-server` 条目提供的 DNS 服务器有效即可。

**Comment by skyairun** [comment]
解决了，我还以为已经内置了。。。

**Comment by 2856571872** [comment]
> 解决了，我还以为已经内置了。。。

解决了能发下完整的conf配置看下么。。
