### ISSUE TITLE
leaf的json在哪里配置

### ISSUE THREAD

**Issue by hhyygg2009** [YtFlow/Maple#15]
leaf的json在哪里配置？写在conf里面吗

**Comment by bdbai** [comment]
点下方的加号按钮新建一个 JSON 配置。编辑完成后右键设为默认即可。

**Comment by hhyygg2009** [comment]
明白了，但是我还是不太会配置Leaf。改了下配置，连接的时候Maple直接崩了

**Comment by hhyygg2009** [comment]
我只想把sock5转成透明代理，不需要其他功能

**Comment by bdbai** [comment]
SOCKS5 服务开在 localhost 吗？因为 UWP 限制不能直接连 localhost 服务。

**Comment by hhyygg2009** [comment]
是在localhost，应该是我设置配置文件不正确才崩溃的。最近我都没空研究怎么使用，看不懂他的文档。

**Comment by bdbai** [comment]
@hhyygg2009 之前代码有问题导致连不上 localhost，v0.4 开始已经修复了。可以再试一下。

**Comment by hhyygg2009** [comment]
用Clash WinTUN解决了😂
