### ISSUE TITLE
请问一下 : 配置文件中的tun-fd 233是不变的吗？

### ISSUE THREAD

**Issue by mikexxma** [YtFlow/Maple#23]
是不是 leaf 对于windows来说没有tun模式？

**Comment by bdbai** [comment]
Maple 会将 UWP VPN 接口和 Leaf 的 TUN 入站进行对接，所以需要留一个 tun 的配置项来启用 TUN 入站功能。

**Comment by mikexxma** [comment]
> Maple 会将 UWP VPN 接口和 Leaf 的 TUN 入站进行对接，所以需要留一个 tun 的配置项来启用 TUN 入站功能。

谢谢

**Comment by bdbai** [comment]
Maple v0.6 开始使用 `tun = auto` 语法，不需要 `tun-fd = 233` 了。
