### ISSUE TITLE
Is it possible to add Hysteria client support ?

### ISSUE THREAD

**Issue by egg1234** [YtFlow/Maple#24]
Is it possible to add Hysteria client support or rewrite a new gui client?

https://github.com/HyNetwork/hysteria  

Thanks!

**Comment by bdbai** [comment]
Please kindly send a feature request to [Leaf](https://github.com/eycorsican/leaf) since Maple is just a VPN front-end of it.

**Comment by egg1234** [comment]
Yes, and is it possible to use Maple as a VPN front-end for Hysteria ? 
Because Hysteria already listens to socks5 port in windows, and also Hysteria has windows binary releases. This scenarios is a bit like v2rayN including v2fly core or xray core windows binary releases.

**Comment by bdbai** [comment]
If you are referring to the Hysteria client written in Go, then it would be impossible because the Go runtime is not tailored for UWP environment. That is why Maple uses Leaf, which is a pure Rust library, instead of v2ray-core or Clash as its core component.
