### ISSUE TITLE
Windows store can't access internet

### ISSUE THREAD

**Issue by lam4o** [YtFlow/Maple#25]
When Maple is enabled the Windows Store loses connection to internet. If I create the VPN connection profile manually (not using "Generate Profile" in the app) it works, and connection is working for UWP store.

What is the difference? Any workarounds to make Generate profile work within the app?

**Comment by bdbai** [comment]
This is actually a known issue. I assume there are some subtle differences between profiles create manually and generated by programming, but yet to find any clues.

**Comment by bdbai** [comment]
I am going to close this issue because currently there is no plan to improve the in-app profile generation. Users are expected to create a profile by themselves.

If anyone has a viable solution, feel free to leave a comment.
