### ISSUE TITLE
Syntax "PROCESS-NAME" in configuration file

### ISSUE THREAD

**Issue by jiashun0011** [YtFlow/Maple#27]
Hi,

I am using Mellow previously and was used to use syntax `PROCESS-NAME` like

```
PROCESS-NAME, trojan.exe, Direct
PROCESS-NAME, putty.exe, Direct
```
Just want to confirm whether it is supported in Maple as well.

Thanks

**Comment by bdbai** [comment]
`PROCESS-NAME` is not supported by Leaf (see https://github.com/eycorsican/leaf/issues/133).

For a UWP app, retrieving process information would be quite limited or even impossible.

**Comment by jiashun0011** [comment]
> `PROCESS-NAME` is not supported by Leaf (see [eycorsican/leaf#133](https://github.com/eycorsican/leaf/issues/133)).
> 
> For a UWP app, retrieving process information would be quite limited or even impossible.

Good to know, thanks.
