### ISSUE TITLE
Configuration editor improvements

### ISSUE THREAD

**Issue by shunia** [YtFlow/Maple#3]
Currently the editor is somehow hard to use because of these reasons:
1. BUG - Paste(ctrl+v) action often outputs duplicate content;
2. BUG - Selection not accurate sometimes if symbols in selection area;
3. BUG(?) - Copied content from the editor, but then not able to paste in other app like SublimeText;
4. Improvements - Context menu not useful and sometimes anoying;
5. Improvements - Feels glitch when editing;

Can not provide my windows version for now but if it's helpful I'll post it later after work.

**Comment by bdbai** [comment]
I feel sorry about your bad experiences while using the editor. The builtin editor is based on the [RichTextBox](https://docs.microsoft.com/en-us/windows/uwp/design/controls-and-patterns/rich-edit-box) which provides few extension points. In a future release, we will consider moving to the plain [TextBox](https://docs.microsoft.com/en-us/windows/uwp/design/controls-and-patterns/text-box) to see if it improves user experience.

Regarding problem 3, it seems like a common issue for UWP apps that clipboard occasionally stops working. Please try relaunching the app and see if it works. Also be careful not to close Maple before you paste anything into another app.

**Comment by shunia** [comment]
> Regarding problem 3, it seems like a common issue for UWP apps that clipboard occasionally stops working. Please try relaunching the app and see if it works. Also be careful not to close Maple before you paste anything into another app.

I'm sure Maple is open and re-open Maple won't fix the problem.

**Comment by bdbai** [comment]
害

**Comment by yume-chan** [comment]
It even allows pasting images.

![image](https://user-images.githubusercontent.com/1330321/179447943-6d872917-f900-4848-9bf7-8c09ae4a8fe7.png)

**Comment by bdbai** [comment]
Hi all, in v0.7.0 we introduced a web-based Monaco editor with rich IntelliSense support for conf files. I hope it will significantly improve your configuration editing experience.
