### ISSUE TITLE
Win10 安装后运行 闪退

### ISSUE THREAD

**Issue by QGB** [YtFlow/Maple#39]
Microsoft Windows [版本 10.0.18363.1316]

**Comment by bdbai** [comment]
Visual Studio 挂载后调试 输出

**Comment by QGB** [comment]
为什么要绑定到Win10，用其他的技术栈如QT，Electron 不行吗？ @YtFlow  @bdbai

**Comment by QGB** [comment]
`UWP VPN 平台作为 TUN 提供商`

**Comment by bdbai** [comment]
行，但酒吧一般不供应炒饭。

**Comment by QGB** [comment]
> 行，但酒吧一般不供应炒饭。

带老干妈去酒吧

**Comment by bdbai** [comment]
> 带老干妈去酒吧

就会被轰出去。

**Comment by iamqk** [comment]
@QGB 我这里也发生了同样的问题
请问你如何解决的？
