### ISSUE TITLE
[Feature Request] A BIG and noticeable start vpn button or clear guidence

### ISSUE THREAD

**Issue by shunia** [YtFlow/Maple#4]
Though Maple can not control vpn flow to connect or disconnect for now, I think it's really useful to make the `Open VPN Settings` button much much more noticeable when opening Maple, it should be in the main screen to tell people to do this.

Or it can be improved to make a clear guidence as `How To Use` in README.

I feel frustrate when I open Maple every time for 10 seconds and then I remembered that I should jump into the vpn settings to connect. And it's worse when I first use Maple, which I think I'm lucky to find how to use it.

**Comment by bdbai** [comment]
These are good points! Much thanks.

**Comment by bdbai** [comment]
An in-app toggle switch (inspired from #5) has been added in v0.6.0, which will definitely to get newcomers started easier. In light of this, I am going to close this issue. Should you have any more ideas to share, feel free to comment here or post new ones.
