### ISSUE TITLE
Package Installation Certificate

### ISSUE THREAD

**Issue by private-number** [YtFlow/Maple#40]
Importing unknown certificate into local machine trusted root authority is not acceptable for security reasons and in any way means opening door for MITM attack.

**Comment by bdbai** [comment]
The key pair we use is strictly for package signing only. Conducting an MITM attack using this certificate is not practical.

For sideloaded apps, it is a common practice to provide a certificate for pre-built app packages. See [Bili.Uwp](https://github.com/Richasy/Bili.Uwp/wiki/%E4%B8%8B%E8%BD%BD%E5%B9%B6%E5%AE%89%E8%A3%85%E5%93%94%E5%93%A9%E7%9A%84%E8%AF%A6%E7%BB%86%E8%AF%B4%E6%98%8E#%E5%B8%B8%E8%A7%84%E4%BD%BF%E7%94%A8%E5%BA%94%E7%94%A8%E5%AE%89%E8%A3%85%E7%A8%8B%E5%BA%8F-app-installer) and [Natsurainko.FluentLauncher](https://github.com/Xcube-Studio/Natsurainko.FluentLauncher/wiki/%E5%A6%82%E4%BD%95%E5%AE%89%E8%A3%85-Msixbundle-%E5%8C%85).

If it is still of concern to you, I suggest manually compiling this app from source.

**Comment by private-number** [comment]
thanks for your reply.
Isn't it better to create a self-sign package script and append it to installation script as pre-requisite to avoid importing CA to trust root?

**Comment by bdbai** [comment]
> Isn't it better to create a self-sign package script and append it to installation script as pre-requisite to avoid importing CA to trust root?

The installation scripts that come with the app package, i.e. `install.ps1` and `Add-AppDevPackage.ps1`, are prepared by Visual Studio packaging pipeline and hence it is not advisable to modify them. The client machine may not have Windows SDK installed where SignTool is provided as well.
