### ISSUE TITLE
如何能支持ipv6功能，我的网络是支持ipv6的，但vpn链接这里无法获取

### ISSUE THREAD

**Issue by wintrue** [YtFlow/Maple#42]
![image](https://user-images.githubusercontent.com/6380530/222043110-27116371-d04c-4dc4-8d38-3e3adc3ecf37.png)

**Comment by bdbai** [comment]
[v0.9.0](https://github.com/YtFlow/Maple/releases/tag/v0.9.0) 添加了 IPv6 支持，可以试一下。
