### ISSUE TITLE
Obfuscation: obfs=tls

### ISSUE THREAD

**Issue by godcookie1314** [YtFlow/Maple#45]
Obfuscation: How is obfs=tls added to the configuration and where do files need to be moved? Because my SS needs to rely on the SS plugin OBFSLOCAL to connect successfully! Hope to solve it soon, thank you!

**Comment by bdbai** [comment]
I have opened a feature proposal for Leaf. Let's see if they are happy with it first.

https://github.com/eycorsican/leaf/issues/362

**Comment by godcookie1314** [comment]
Thank you very much！

**Comment by bdbai** [comment]
Supported in [v0.9.0](https://github.com/YtFlow/Maple/releases/tag/v0.9.0).
