### ISSUE TITLE
在windows下vpn配置会影响到hyper-v虚拟机

### ISSUE THREAD

**Issue by KoinuDayo** [YtFlow/Maple#48]
我hyper-v虚拟机上跑了个xray做中转，用maple ss连接虚拟机上的xray，结果把虚拟机也代理了，绕起来了，怎么解。
虚拟机网卡是桥接物理网卡，和宿主共享一个物理网卡

**Comment by bdbai** [comment]
为什么不直接在宿主环境运行 xray 呢？

有试过给上游服务器加一个 Direct 规则吗？

**Comment by KoinuDayo** [comment]
> 为什么不直接在宿主环境运行 xray 呢？
不知道为什么在虚拟机下xray的延迟会明显降低
> 有试过给上游服务器加一个 Direct 规则吗？
没试过，具体该怎么做

**Comment by bdbai** [comment]
> 没试过，具体该怎么做

取决于你的上游代理服务器地址类型，在 Maple 配置文件的 `[Rule]` 区域开头加上

```ini
IP-CIDR, 114.51.4.191/32, Direct
```
或
```ini
DOMAIN, my.proxy.server.com, Direct
```
其中 `114.51.4.191` 和 `my.proxy.server.com` 分别是代理服务器的 IP 和域名。

**Comment by KoinuDayo** [comment]
```
[General]
loglevel = error
tun = auto
dns-server = 8.8.8.8, 1.1.1.1, 223.5.5.5, 114.114.114.114

[Proxy]
# Define your proxy server here
server1 = ss, 192.168.1.10, 65530, encrypt-method=aes-256-gcm, password=1145141919
Direct =direct
[Rule]
# `server1` refers to one of the defined proxy server
FINAL, server1
IP-CIDR, 1145:1419:1981:09f:54ff:fff:ffff:233/64, Direct
```
我这样加了一个直连的地址，但是没效果，是leaf不支持ipv6的rule设置吗，还是说我哪设置错了。

**Comment by bdbai** [comment]
@KoinuDayo `/64` 换成 `/128`

**Comment by KoinuDayo** [comment]
> @KoinuDayo `/64` 换成 `/128`

结果一样，没效果。我`/64`是在终端ip addr里复制的

**Comment by bdbai** [comment]
想了一下，现在 Leaf 的出站接口是统一指定的，普通的 conf 配置应该很难做到不同出站走不同接口。或许你可以试试给虚拟机配一个 external switch，然后让 xray 绑定到物理接口？

**Comment by KoinuDayo** [comment]
> 想了一下，现在 Leaf 的出站接口是统一指定的，普通的 conf 配置应该很难做到不同出站走不同接口。或许你可以试试给虚拟机配一个 external switch，然后让 xray 绑定到物理接口？

不知道为什么，我的hyper-v管理器不允许我再创建一个switch。
我想了想还是给xray设置个socks5入站然后再用windows的系统代理进行代理吧，之前系统代理不能代理虚拟机折腾我半天，最后还是回到系统代理
