### ISSUE TITLE
I have vless config but I don't know how to apply it and use it in Maple

### ISSUE THREAD

**Issue by Your-Best-Friend86** [YtFlow/Maple#50]
Hi my config is something like this in apps like v2rayN:
![image](https://github.com/YtFlow/Maple/assets/80213487/01b950d6-9859-4ee5-a369-2100dd1f05c7)

and its like this in Netch (same config):
![image](https://github.com/YtFlow/Maple/assets/80213487/906775e3-3e6e-4d3b-9e94-e7b30ece6603)

can someone help me apply it? Netch is crashing after Starting and connecting and annoying and V2rayN is not effecting whole system (can't be used for Gaming) thats why I need Maple, something that can effect whole system like Netch but I can't config it

This is the Config it self:
`vless://********-****-****-****-************@callofduty.gamer2sky.com:****?encryption=none&security=none&type=ws&host=callofduty.gamer2sky.com&path=%2F#%40vanenshii-23apr`

**Comment by bdbai** [comment]
Leaf does not support vless protocol, but you can point Maple to V2rayN SOCKS5 inbound port. Remember to exclude the upstream server and add a loopback exemption for Maple.

Also see https://github.com/YtFlow/Maple/issues/38
