### ISSUE TITLE
[Feature Request]Support EXTERNAL rules

### ISSUE THREAD

**Issue by perqin** [YtFlow/Maple#6]
See [this issue](https://github.com/eycorsican/leaf/issues/124) for the context.

In a nutshell, Maple could ask the user for the `*.dat/*.site` files, and make Leaf be able to find them by modifying the `ASSET_LOCATION` env var.

**Comment by bdbai** [comment]
May I know if you have started working on this already?

**Comment by perqin** [comment]
No, not yet. I just hack Leaf's code to make absolute path work last weekend. And I'm not an experienced UWP developer :(

**Comment by bdbai** [comment]
Landed in https://github.com/YtFlow/Maple/commit/51f812d88f65d32525f782c2b75d2bf9155f74c3
