### ISSUE TITLE
访问如下网站,leaf内存无法释放

### ISSUE THREAD

**Issue by Xx0101** [YtFlow/Maple#7]
https://whoer.net/zh

**Comment by Xx0101** [comment]
> 您是否可以提供更多信息关于这个问题？比如：如何你测量内存使用率？初始测量值？哪些操作您已经完成的？最终测量值？

我的电脑运行起来之后全局代理模式下,观察内存使用,访问上面的dns检测网站会发现内存从5到7,再到12,一直增长,从未下降,尤其是打开多个上述网站的时候,您可以尝试下

**Comment by bdbai** [comment]
关闭**整个浏览器窗口**后，内存占用是否下降了呢？

**Comment by Xx0101** [comment]
> 关闭**整个浏览器窗口**后，内存占用是否下降了呢？

就是没有下降才头疼,一直被维持住了,只升不降,其他网站都好的,这个检测的网站就降不下来

**Comment by bdbai** [comment]
> https://whoer.net/zh

这个网站我本地打不开，代理也被 Cloudflare 屏蔽了。简单看了一下好像没有问题，等新版发布了再试试吧，如果还漏内存再来研究研究。
